// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQmvbAXIWOCHBOweAesGxwKprebx1y0RI',
    appId: '1:137425166706:web:109ead11f0b6df8fbcbdeb',
    messagingSenderId: '137425166706',
    projectId: 'flutix054',
    authDomain: 'flutix054.firebaseapp.com',
    storageBucket: 'flutix054.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuMwMdYxaZf6YixTs0HLAGFhHRjY6LjEg',
    appId: '1:137425166706:android:f9827bd2574beea2bcbdeb',
    messagingSenderId: '137425166706',
    projectId: 'flutix054',
    storageBucket: 'flutix054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOXY4oyW8Tm8z3HJQVk9Xxsu4Ld03xbkQ',
    appId: '1:137425166706:ios:11d7469e7733512cbcbdeb',
    messagingSenderId: '137425166706',
    projectId: 'flutix054',
    storageBucket: 'flutix054.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOXY4oyW8Tm8z3HJQVk9Xxsu4Ld03xbkQ',
    appId: '1:137425166706:ios:5d10066c03994d90bcbdeb',
    messagingSenderId: '137425166706',
    projectId: 'flutix054',
    storageBucket: 'flutix054.appspot.com',
    iosBundleId: 'com.example.flutter1.RunnerTests',
  );
}
